// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/network/protocol/client_messages.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReconnectPayload 断线重连请求
type ReconnectPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectPayload) Reset() {
	*x = ReconnectPayload{}
	mi := &file_internal_network_protocol_client_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectPayload) ProtoMessage() {}

func (x *ReconnectPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_client_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectPayload.ProtoReflect.Descriptor instead.
func (*ReconnectPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_client_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ReconnectPayload) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReconnectPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// PingPayload 心跳请求
type PingPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingPayload) Reset() {
	*x = PingPayload{}
	mi := &file_internal_network_protocol_client_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingPayload) ProtoMessage() {}

func (x *PingPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_client_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingPayload.ProtoReflect.Descriptor instead.
func (*PingPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_client_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PingPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// JoinRoomPayload 加入房间请求
type JoinRoomPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCode      string                 `protobuf:"bytes,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomPayload) Reset() {
	*x = JoinRoomPayload{}
	mi := &file_internal_network_protocol_client_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomPayload) ProtoMessage() {}

func (x *JoinRoomPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_client_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomPayload.ProtoReflect.Descriptor instead.
func (*JoinRoomPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_client_messages_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRoomPayload) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

// BidPayload 叫地主请求
type BidPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           bool                   `protobuf:"varint,1,opt,name=bid,proto3" json:"bid,omitempty"` // true = 叫地主, false = 不叫
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidPayload) Reset() {
	*x = BidPayload{}
	mi := &file_internal_network_protocol_client_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidPayload) ProtoMessage() {}

func (x *BidPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_client_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidPayload.ProtoReflect.Descriptor instead.
func (*BidPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_client_messages_proto_rawDescGZIP(), []int{3}
}

func (x *BidPayload) GetBid() bool {
	if x != nil {
		return x.Bid
	}
	return false
}

// PlayCardsPayload 出牌请求
type PlayCardsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*CardInfo            `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayCardsPayload) Reset() {
	*x = PlayCardsPayload{}
	mi := &file_internal_network_protocol_client_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayCardsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayCardsPayload) ProtoMessage() {}

func (x *PlayCardsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_client_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayCardsPayload.ProtoReflect.Descriptor instead.
func (*PlayCardsPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_client_messages_proto_rawDescGZIP(), []int{4}
}

func (x *PlayCardsPayload) GetCards() []*CardInfo {
	if x != nil {
		return x.Cards
	}
	return nil
}

// GetLeaderboardPayload 获取排行榜请求
type GetLeaderboardPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`      // total/daily/weekly
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // 偏移量
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`   // 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardPayload) Reset() {
	*x = GetLeaderboardPayload{}
	mi := &file_internal_network_protocol_client_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardPayload) ProtoMessage() {}

func (x *GetLeaderboardPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_client_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardPayload.ProtoReflect.Descriptor instead.
func (*GetLeaderboardPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_client_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetLeaderboardPayload) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetLeaderboardPayload) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetLeaderboardPayload) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_internal_network_protocol_client_messages_proto protoreflect.FileDescriptor

const file_internal_network_protocol_client_messages_proto_rawDesc = "" +
	"\n" +
	"/internal/network/protocol/client_messages.proto\x12\bprotocol\x1a&internal/network/protocol/common.proto\"E\n" +
	"\x10ReconnectPayload\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"+\n" +
	"\vPingPayload\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\".\n" +
	"\x0fJoinRoomPayload\x12\x1b\n" +
	"\troom_code\x18\x01 \x01(\tR\broomCode\"\x1e\n" +
	"\n" +
	"BidPayload\x12\x10\n" +
	"\x03bid\x18\x01 \x01(\bR\x03bid\"<\n" +
	"\x10PlayCardsPayload\x12(\n" +
	"\x05cards\x18\x01 \x03(\v2\x12.protocol.CardInfoR\x05cards\"Y\n" +
	"\x15GetLeaderboardPayload\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limitBEZCgithub.com/palemoky/fight-the-landlord/internal/network/protocol/pbb\x06proto3"

var (
	file_internal_network_protocol_client_messages_proto_rawDescOnce sync.Once
	file_internal_network_protocol_client_messages_proto_rawDescData []byte
)

func file_internal_network_protocol_client_messages_proto_rawDescGZIP() []byte {
	file_internal_network_protocol_client_messages_proto_rawDescOnce.Do(func() {
		file_internal_network_protocol_client_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_network_protocol_client_messages_proto_rawDesc), len(file_internal_network_protocol_client_messages_proto_rawDesc)))
	})
	return file_internal_network_protocol_client_messages_proto_rawDescData
}

var (
	file_internal_network_protocol_client_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
	file_internal_network_protocol_client_messages_proto_goTypes  = []any{
		(*ReconnectPayload)(nil),      // 0: protocol.ReconnectPayload
		(*PingPayload)(nil),           // 1: protocol.PingPayload
		(*JoinRoomPayload)(nil),       // 2: protocol.JoinRoomPayload
		(*BidPayload)(nil),            // 3: protocol.BidPayload
		(*PlayCardsPayload)(nil),      // 4: protocol.PlayCardsPayload
		(*GetLeaderboardPayload)(nil), // 5: protocol.GetLeaderboardPayload
		(*CardInfo)(nil),              // 6: protocol.CardInfo
	}
)

var file_internal_network_protocol_client_messages_proto_depIdxs = []int32{
	6, // 0: protocol.PlayCardsPayload.cards:type_name -> protocol.CardInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_network_protocol_client_messages_proto_init() }
func file_internal_network_protocol_client_messages_proto_init() {
	if File_internal_network_protocol_client_messages_proto != nil {
		return
	}
	file_internal_network_protocol_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_network_protocol_client_messages_proto_rawDesc), len(file_internal_network_protocol_client_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_network_protocol_client_messages_proto_goTypes,
		DependencyIndexes: file_internal_network_protocol_client_messages_proto_depIdxs,
		MessageInfos:      file_internal_network_protocol_client_messages_proto_msgTypes,
	}.Build()
	File_internal_network_protocol_client_messages_proto = out.File
	file_internal_network_protocol_client_messages_proto_goTypes = nil
	file_internal_network_protocol_client_messages_proto_depIdxs = nil
}
