// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/network/protocol/common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CardInfo 牌信息
type CardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suit          int32                  `protobuf:"varint,1,opt,name=suit,proto3" json:"suit,omitempty"`   // 花色: 0=黑桃, 1=红心, 2=梅花, 3=方块, 4=王
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`   // 点数: 3-17 (3-2, 小王=16, 大王=17)
	Color         int32                  `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"` // 颜色: 0=黑, 1=红
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardInfo) Reset() {
	*x = CardInfo{}
	mi := &file_internal_network_protocol_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardInfo) ProtoMessage() {}

func (x *CardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardInfo.ProtoReflect.Descriptor instead.
func (*CardInfo) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_common_proto_rawDescGZIP(), []int{0}
}

func (x *CardInfo) GetSuit() int32 {
	if x != nil {
		return x.Suit
	}
	return 0
}

func (x *CardInfo) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *CardInfo) GetColor() int32 {
	if x != nil {
		return x.Color
	}
	return 0
}

// PlayerInfo 玩家信息
type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Seat          int32                  `protobuf:"varint,3,opt,name=seat,proto3" json:"seat,omitempty"`                               // 座位号 0-2
	Ready         bool                   `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`                             // 是否准备
	IsLandlord    bool                   `protobuf:"varint,5,opt,name=is_landlord,json=isLandlord,proto3" json:"is_landlord,omitempty"` // 是否是地主
	CardsCount    int32                  `protobuf:"varint,6,opt,name=cards_count,json=cardsCount,proto3" json:"cards_count,omitempty"` // 手牌数量
	Online        bool                   `protobuf:"varint,7,opt,name=online,proto3" json:"online,omitempty"`                           // 是否在线
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_internal_network_protocol_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_common_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInfo) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *PlayerInfo) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *PlayerInfo) GetIsLandlord() bool {
	if x != nil {
		return x.IsLandlord
	}
	return false
}

func (x *PlayerInfo) GetCardsCount() int32 {
	if x != nil {
		return x.CardsCount
	}
	return 0
}

func (x *PlayerInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

// PlayerHand 玩家手牌信息（用于游戏结束展示）
type PlayerHand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Cards         []*CardInfo            `protobuf:"bytes,3,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerHand) Reset() {
	*x = PlayerHand{}
	mi := &file_internal_network_protocol_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerHand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerHand) ProtoMessage() {}

func (x *PlayerHand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerHand.ProtoReflect.Descriptor instead.
func (*PlayerHand) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_common_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerHand) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerHand) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerHand) GetCards() []*CardInfo {
	if x != nil {
		return x.Cards
	}
	return nil
}

// GameStateDTO 游戏状态数据传输对象（用于重连恢复）
type GameStateDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`                                      // bidding/playing
	Players       []*PlayerInfo          `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`                                  // 所有玩家信息
	Hand          []*CardInfo            `protobuf:"bytes,3,rep,name=hand,proto3" json:"hand,omitempty"`                                        // 自己的手牌
	LandlordCards []*CardInfo            `protobuf:"bytes,4,rep,name=landlord_cards,json=landlordCards,proto3" json:"landlord_cards,omitempty"` // 底牌
	CurrentTurn   string                 `protobuf:"bytes,5,opt,name=current_turn,json=currentTurn,proto3" json:"current_turn,omitempty"`       // 当前回合玩家 ID
	LastPlayed    []*CardInfo            `protobuf:"bytes,6,rep,name=last_played,json=lastPlayed,proto3" json:"last_played,omitempty"`          // 上家出的牌
	LastPlayerId  string                 `protobuf:"bytes,7,opt,name=last_player_id,json=lastPlayerId,proto3" json:"last_player_id,omitempty"`  // 上家 ID
	MustPlay      bool                   `protobuf:"varint,8,opt,name=must_play,json=mustPlay,proto3" json:"must_play,omitempty"`               // 是否必须出牌
	CanBeat       bool                   `protobuf:"varint,9,opt,name=can_beat,json=canBeat,proto3" json:"can_beat,omitempty"`                  // 是否能打过
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateDTO) Reset() {
	*x = GameStateDTO{}
	mi := &file_internal_network_protocol_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateDTO) ProtoMessage() {}

func (x *GameStateDTO) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateDTO.ProtoReflect.Descriptor instead.
func (*GameStateDTO) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_common_proto_rawDescGZIP(), []int{3}
}

func (x *GameStateDTO) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *GameStateDTO) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameStateDTO) GetHand() []*CardInfo {
	if x != nil {
		return x.Hand
	}
	return nil
}

func (x *GameStateDTO) GetLandlordCards() []*CardInfo {
	if x != nil {
		return x.LandlordCards
	}
	return nil
}

func (x *GameStateDTO) GetCurrentTurn() string {
	if x != nil {
		return x.CurrentTurn
	}
	return ""
}

func (x *GameStateDTO) GetLastPlayed() []*CardInfo {
	if x != nil {
		return x.LastPlayed
	}
	return nil
}

func (x *GameStateDTO) GetLastPlayerId() string {
	if x != nil {
		return x.LastPlayerId
	}
	return ""
}

func (x *GameStateDTO) GetMustPlay() bool {
	if x != nil {
		return x.MustPlay
	}
	return false
}

func (x *GameStateDTO) GetCanBeat() bool {
	if x != nil {
		return x.CanBeat
	}
	return false
}

// LeaderboardEntry 排行榜条目
type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,3,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	Wins          int32                  `protobuf:"varint,5,opt,name=wins,proto3" json:"wins,omitempty"`
	WinRate       float64                `protobuf:"fixed64,6,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_internal_network_protocol_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_common_proto_rawDescGZIP(), []int{4}
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LeaderboardEntry) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderboardEntry) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *LeaderboardEntry) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

// RoomListItem 房间列表项
type RoomListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCode      string                 `protobuf:"bytes,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	PlayerCount   int32                  `protobuf:"varint,2,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,3,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListItem) Reset() {
	*x = RoomListItem{}
	mi := &file_internal_network_protocol_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListItem) ProtoMessage() {}

func (x *RoomListItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListItem.ProtoReflect.Descriptor instead.
func (*RoomListItem) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_common_proto_rawDescGZIP(), []int{5}
}

func (x *RoomListItem) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *RoomListItem) GetPlayerCount() int32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *RoomListItem) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

var File_internal_network_protocol_common_proto protoreflect.FileDescriptor

const file_internal_network_protocol_common_proto_rawDesc = "" +
	"\n" +
	"&internal/network/protocol/common.proto\x12\bprotocol\"H\n" +
	"\bCardInfo\x12\x12\n" +
	"\x04suit\x18\x01 \x01(\x05R\x04suit\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\x12\x14\n" +
	"\x05color\x18\x03 \x01(\x05R\x05color\"\xb4\x01\n" +
	"\n" +
	"PlayerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04seat\x18\x03 \x01(\x05R\x04seat\x12\x14\n" +
	"\x05ready\x18\x04 \x01(\bR\x05ready\x12\x1f\n" +
	"\vis_landlord\x18\x05 \x01(\bR\n" +
	"isLandlord\x12\x1f\n" +
	"\vcards_count\x18\x06 \x01(\x05R\n" +
	"cardsCount\x12\x16\n" +
	"\x06online\x18\a \x01(\bR\x06online\"t\n" +
	"\n" +
	"PlayerHand\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12(\n" +
	"\x05cards\x18\x03 \x03(\v2\x12.protocol.CardInfoR\x05cards\"\xed\x02\n" +
	"\fGameStateDTO\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12.\n" +
	"\aplayers\x18\x02 \x03(\v2\x14.protocol.PlayerInfoR\aplayers\x12&\n" +
	"\x04hand\x18\x03 \x03(\v2\x12.protocol.CardInfoR\x04hand\x129\n" +
	"\x0elandlord_cards\x18\x04 \x03(\v2\x12.protocol.CardInfoR\rlandlordCards\x12!\n" +
	"\fcurrent_turn\x18\x05 \x01(\tR\vcurrentTurn\x123\n" +
	"\vlast_played\x18\x06 \x03(\v2\x12.protocol.CardInfoR\n" +
	"lastPlayed\x12$\n" +
	"\x0elast_player_id\x18\a \x01(\tR\flastPlayerId\x12\x1b\n" +
	"\tmust_play\x18\b \x01(\bR\bmustPlay\x12\x19\n" +
	"\bcan_beat\x18\t \x01(\bR\acanBeat\"\xa9\x01\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x03 \x01(\tR\n" +
	"playerName\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x12\n" +
	"\x04wins\x18\x05 \x01(\x05R\x04wins\x12\x19\n" +
	"\bwin_rate\x18\x06 \x01(\x01R\awinRate\"o\n" +
	"\fRoomListItem\x12\x1b\n" +
	"\troom_code\x18\x01 \x01(\tR\broomCode\x12!\n" +
	"\fplayer_count\x18\x02 \x01(\x05R\vplayerCount\x12\x1f\n" +
	"\vmax_players\x18\x03 \x01(\x05R\n" +
	"maxPlayersBEZCgithub.com/palemoky/fight-the-landlord/internal/network/protocol/pbb\x06proto3"

var (
	file_internal_network_protocol_common_proto_rawDescOnce sync.Once
	file_internal_network_protocol_common_proto_rawDescData []byte
)

func file_internal_network_protocol_common_proto_rawDescGZIP() []byte {
	file_internal_network_protocol_common_proto_rawDescOnce.Do(func() {
		file_internal_network_protocol_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_network_protocol_common_proto_rawDesc), len(file_internal_network_protocol_common_proto_rawDesc)))
	})
	return file_internal_network_protocol_common_proto_rawDescData
}

var file_internal_network_protocol_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_network_protocol_common_proto_goTypes = []any{
	(*CardInfo)(nil),         // 0: protocol.CardInfo
	(*PlayerInfo)(nil),       // 1: protocol.PlayerInfo
	(*PlayerHand)(nil),       // 2: protocol.PlayerHand
	(*GameStateDTO)(nil),     // 3: protocol.GameStateDTO
	(*LeaderboardEntry)(nil), // 4: protocol.LeaderboardEntry
	(*RoomListItem)(nil),     // 5: protocol.RoomListItem
}
var file_internal_network_protocol_common_proto_depIdxs = []int32{
	0, // 0: protocol.PlayerHand.cards:type_name -> protocol.CardInfo
	1, // 1: protocol.GameStateDTO.players:type_name -> protocol.PlayerInfo
	0, // 2: protocol.GameStateDTO.hand:type_name -> protocol.CardInfo
	0, // 3: protocol.GameStateDTO.landlord_cards:type_name -> protocol.CardInfo
	0, // 4: protocol.GameStateDTO.last_played:type_name -> protocol.CardInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_network_protocol_common_proto_init() }
func file_internal_network_protocol_common_proto_init() {
	if File_internal_network_protocol_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_network_protocol_common_proto_rawDesc), len(file_internal_network_protocol_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_network_protocol_common_proto_goTypes,
		DependencyIndexes: file_internal_network_protocol_common_proto_depIdxs,
		MessageInfos:      file_internal_network_protocol_common_proto_msgTypes,
	}.Build()
	File_internal_network_protocol_common_proto = out.File
	file_internal_network_protocol_common_proto_goTypes = nil
	file_internal_network_protocol_common_proto_depIdxs = nil
}
