// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/network/protocol/proto/game_messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RoomCreatedPayload 房间创建成功响应
type RoomCreatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCode      string                 `protobuf:"bytes,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	Player        *PlayerInfo            `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCreatedPayload) Reset() {
	*x = RoomCreatedPayload{}
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreatedPayload) ProtoMessage() {}

func (x *RoomCreatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreatedPayload.ProtoReflect.Descriptor instead.
func (*RoomCreatedPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_game_messages_proto_rawDescGZIP(), []int{0}
}

func (x *RoomCreatedPayload) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *RoomCreatedPayload) GetPlayer() *PlayerInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

// RoomJoinedPayload 加入房间成功响应
type RoomJoinedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCode      string                 `protobuf:"bytes,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	Player        *PlayerInfo            `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	Players       []*PlayerInfo          `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomJoinedPayload) Reset() {
	*x = RoomJoinedPayload{}
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomJoinedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoinedPayload) ProtoMessage() {}

func (x *RoomJoinedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoinedPayload.ProtoReflect.Descriptor instead.
func (*RoomJoinedPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_game_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RoomJoinedPayload) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *RoomJoinedPayload) GetPlayer() *PlayerInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *RoomJoinedPayload) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

// PlayerJoinedPayload 其他玩家加入通知
type PlayerJoinedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerInfo            `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoinedPayload) Reset() {
	*x = PlayerJoinedPayload{}
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoinedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoinedPayload) ProtoMessage() {}

func (x *PlayerJoinedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoinedPayload.ProtoReflect.Descriptor instead.
func (*PlayerJoinedPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_game_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerJoinedPayload) GetPlayer() *PlayerInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

// PlayerLeftPayload 玩家离开通知
type PlayerLeftPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeftPayload) Reset() {
	*x = PlayerLeftPayload{}
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeftPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeftPayload) ProtoMessage() {}

func (x *PlayerLeftPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeftPayload.ProtoReflect.Descriptor instead.
func (*PlayerLeftPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_game_messages_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerLeftPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerLeftPayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// PlayerReadyPayload 玩家准备通知
type PlayerReadyPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerReadyPayload) Reset() {
	*x = PlayerReadyPayload{}
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerReadyPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReadyPayload) ProtoMessage() {}

func (x *PlayerReadyPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReadyPayload.ProtoReflect.Descriptor instead.
func (*PlayerReadyPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_game_messages_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerReadyPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerReadyPayload) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

// GameStartPayload 游戏开始通知
type GameStartPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerInfo          `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStartPayload) Reset() {
	*x = GameStartPayload{}
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStartPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStartPayload) ProtoMessage() {}

func (x *GameStartPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStartPayload.ProtoReflect.Descriptor instead.
func (*GameStartPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_game_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GameStartPayload) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

// DealCardsPayload 发牌通知
type DealCardsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*CardInfo            `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	BottomCards   []*CardInfo            `protobuf:"bytes,2,rep,name=bottom_cards,json=bottomCards,proto3" json:"bottom_cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealCardsPayload) Reset() {
	*x = DealCardsPayload{}
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealCardsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealCardsPayload) ProtoMessage() {}

func (x *DealCardsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealCardsPayload.ProtoReflect.Descriptor instead.
func (*DealCardsPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_game_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DealCardsPayload) GetCards() []*CardInfo {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *DealCardsPayload) GetBottomCards() []*CardInfo {
	if x != nil {
		return x.BottomCards
	}
	return nil
}

// BidTurnPayload 轮到叫地主通知
type BidTurnPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Timeout       int64                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidTurnPayload) Reset() {
	*x = BidTurnPayload{}
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidTurnPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidTurnPayload) ProtoMessage() {}

func (x *BidTurnPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidTurnPayload.ProtoReflect.Descriptor instead.
func (*BidTurnPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_game_messages_proto_rawDescGZIP(), []int{7}
}

func (x *BidTurnPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *BidTurnPayload) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// BidResultPayload 叫地主结果通知
type BidResultPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Bid           bool                   `protobuf:"varint,3,opt,name=bid,proto3" json:"bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResultPayload) Reset() {
	*x = BidResultPayload{}
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResultPayload) ProtoMessage() {}

func (x *BidResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResultPayload.ProtoReflect.Descriptor instead.
func (*BidResultPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_game_messages_proto_rawDescGZIP(), []int{8}
}

func (x *BidResultPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *BidResultPayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *BidResultPayload) GetBid() bool {
	if x != nil {
		return x.Bid
	}
	return false
}

// LandlordPayload 地主确定通知
type LandlordPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	BottomCards   []*CardInfo            `protobuf:"bytes,3,rep,name=bottom_cards,json=bottomCards,proto3" json:"bottom_cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandlordPayload) Reset() {
	*x = LandlordPayload{}
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandlordPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlordPayload) ProtoMessage() {}

func (x *LandlordPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlordPayload.ProtoReflect.Descriptor instead.
func (*LandlordPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_game_messages_proto_rawDescGZIP(), []int{9}
}

func (x *LandlordPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LandlordPayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *LandlordPayload) GetBottomCards() []*CardInfo {
	if x != nil {
		return x.BottomCards
	}
	return nil
}

// PlayTurnPayload 轮到出牌通知
type PlayTurnPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Timeout       int64                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MustPlay      bool                   `protobuf:"varint,3,opt,name=must_play,json=mustPlay,proto3" json:"must_play,omitempty"`
	CanBeat       bool                   `protobuf:"varint,4,opt,name=can_beat,json=canBeat,proto3" json:"can_beat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayTurnPayload) Reset() {
	*x = PlayTurnPayload{}
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayTurnPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayTurnPayload) ProtoMessage() {}

func (x *PlayTurnPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayTurnPayload.ProtoReflect.Descriptor instead.
func (*PlayTurnPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_game_messages_proto_rawDescGZIP(), []int{10}
}

func (x *PlayTurnPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayTurnPayload) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *PlayTurnPayload) GetMustPlay() bool {
	if x != nil {
		return x.MustPlay
	}
	return false
}

func (x *PlayTurnPayload) GetCanBeat() bool {
	if x != nil {
		return x.CanBeat
	}
	return false
}

// CardPlayedPayload 出牌通知
type CardPlayedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Cards         []*CardInfo            `protobuf:"bytes,3,rep,name=cards,proto3" json:"cards,omitempty"`
	CardsLeft     int64                  `protobuf:"varint,4,opt,name=cards_left,json=cardsLeft,proto3" json:"cards_left,omitempty"`
	HandType      string                 `protobuf:"bytes,5,opt,name=hand_type,json=handType,proto3" json:"hand_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardPlayedPayload) Reset() {
	*x = CardPlayedPayload{}
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardPlayedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardPlayedPayload) ProtoMessage() {}

func (x *CardPlayedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardPlayedPayload.ProtoReflect.Descriptor instead.
func (*CardPlayedPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_game_messages_proto_rawDescGZIP(), []int{11}
}

func (x *CardPlayedPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CardPlayedPayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *CardPlayedPayload) GetCards() []*CardInfo {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *CardPlayedPayload) GetCardsLeft() int64 {
	if x != nil {
		return x.CardsLeft
	}
	return 0
}

func (x *CardPlayedPayload) GetHandType() string {
	if x != nil {
		return x.HandType
	}
	return ""
}

// PlayerPassPayload 不出通知
type PlayerPassPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerPassPayload) Reset() {
	*x = PlayerPassPayload{}
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerPassPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPassPayload) ProtoMessage() {}

func (x *PlayerPassPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPassPayload.ProtoReflect.Descriptor instead.
func (*PlayerPassPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_game_messages_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerPassPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerPassPayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// GameOverPayload 游戏结束通知
type GameOverPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinnerId      string                 `protobuf:"bytes,1,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	WinnerName    string                 `protobuf:"bytes,2,opt,name=winner_name,json=winnerName,proto3" json:"winner_name,omitempty"`
	IsLandlord    bool                   `protobuf:"varint,3,opt,name=is_landlord,json=isLandlord,proto3" json:"is_landlord,omitempty"`
	PlayerHands   []*PlayerHand          `protobuf:"bytes,4,rep,name=player_hands,json=playerHands,proto3" json:"player_hands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOverPayload) Reset() {
	*x = GameOverPayload{}
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOverPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOverPayload) ProtoMessage() {}

func (x *GameOverPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_game_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOverPayload.ProtoReflect.Descriptor instead.
func (*GameOverPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_game_messages_proto_rawDescGZIP(), []int{13}
}

func (x *GameOverPayload) GetWinnerId() string {
	if x != nil {
		return x.WinnerId
	}
	return ""
}

func (x *GameOverPayload) GetWinnerName() string {
	if x != nil {
		return x.WinnerName
	}
	return ""
}

func (x *GameOverPayload) GetIsLandlord() bool {
	if x != nil {
		return x.IsLandlord
	}
	return false
}

func (x *GameOverPayload) GetPlayerHands() []*PlayerHand {
	if x != nil {
		return x.PlayerHands
	}
	return nil
}

var File_internal_network_protocol_proto_game_messages_proto protoreflect.FileDescriptor

const file_internal_network_protocol_proto_game_messages_proto_rawDesc = "" +
	"\n" +
	"3internal/network/protocol/proto/game_messages.proto\x12\bprotocol\x1a,internal/network/protocol/proto/common.proto\"_\n" +
	"\x12RoomCreatedPayload\x12\x1b\n" +
	"\troom_code\x18\x01 \x01(\tR\broomCode\x12,\n" +
	"\x06player\x18\x02 \x01(\v2\x14.protocol.PlayerInfoR\x06player\"\x8e\x01\n" +
	"\x11RoomJoinedPayload\x12\x1b\n" +
	"\troom_code\x18\x01 \x01(\tR\broomCode\x12,\n" +
	"\x06player\x18\x02 \x01(\v2\x14.protocol.PlayerInfoR\x06player\x12.\n" +
	"\aplayers\x18\x03 \x03(\v2\x14.protocol.PlayerInfoR\aplayers\"C\n" +
	"\x13PlayerJoinedPayload\x12,\n" +
	"\x06player\x18\x01 \x01(\v2\x14.protocol.PlayerInfoR\x06player\"Q\n" +
	"\x11PlayerLeftPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"G\n" +
	"\x12PlayerReadyPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\"B\n" +
	"\x10GameStartPayload\x12.\n" +
	"\aplayers\x18\x01 \x03(\v2\x14.protocol.PlayerInfoR\aplayers\"s\n" +
	"\x10DealCardsPayload\x12(\n" +
	"\x05cards\x18\x01 \x03(\v2\x12.protocol.CardInfoR\x05cards\x125\n" +
	"\fbottom_cards\x18\x02 \x03(\v2\x12.protocol.CardInfoR\vbottomCards\"G\n" +
	"\x0eBidTurnPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x03R\atimeout\"b\n" +
	"\x10BidResultPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x10\n" +
	"\x03bid\x18\x03 \x01(\bR\x03bid\"\x86\x01\n" +
	"\x0fLandlordPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x125\n" +
	"\fbottom_cards\x18\x03 \x03(\v2\x12.protocol.CardInfoR\vbottomCards\"\x80\x01\n" +
	"\x0fPlayTurnPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x03R\atimeout\x12\x1b\n" +
	"\tmust_play\x18\x03 \x01(\bR\bmustPlay\x12\x19\n" +
	"\bcan_beat\x18\x04 \x01(\bR\acanBeat\"\xb7\x01\n" +
	"\x11CardPlayedPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12(\n" +
	"\x05cards\x18\x03 \x03(\v2\x12.protocol.CardInfoR\x05cards\x12\x1d\n" +
	"\n" +
	"cards_left\x18\x04 \x01(\x03R\tcardsLeft\x12\x1b\n" +
	"\thand_type\x18\x05 \x01(\tR\bhandType\"Q\n" +
	"\x11PlayerPassPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"\xa9\x01\n" +
	"\x0fGameOverPayload\x12\x1b\n" +
	"\twinner_id\x18\x01 \x01(\tR\bwinnerId\x12\x1f\n" +
	"\vwinner_name\x18\x02 \x01(\tR\n" +
	"winnerName\x12\x1f\n" +
	"\vis_landlord\x18\x03 \x01(\bR\n" +
	"isLandlord\x127\n" +
	"\fplayer_hands\x18\x04 \x03(\v2\x14.protocol.PlayerHandR\vplayerHandsBEZCgithub.com/palemoky/fight-the-landlord/internal/network/protocol/pbb\x06proto3"

var (
	file_internal_network_protocol_proto_game_messages_proto_rawDescOnce sync.Once
	file_internal_network_protocol_proto_game_messages_proto_rawDescData []byte
)

func file_internal_network_protocol_proto_game_messages_proto_rawDescGZIP() []byte {
	file_internal_network_protocol_proto_game_messages_proto_rawDescOnce.Do(func() {
		file_internal_network_protocol_proto_game_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_network_protocol_proto_game_messages_proto_rawDesc), len(file_internal_network_protocol_proto_game_messages_proto_rawDesc)))
	})
	return file_internal_network_protocol_proto_game_messages_proto_rawDescData
}

var file_internal_network_protocol_proto_game_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_network_protocol_proto_game_messages_proto_goTypes = []any{
	(*RoomCreatedPayload)(nil),  // 0: protocol.RoomCreatedPayload
	(*RoomJoinedPayload)(nil),   // 1: protocol.RoomJoinedPayload
	(*PlayerJoinedPayload)(nil), // 2: protocol.PlayerJoinedPayload
	(*PlayerLeftPayload)(nil),   // 3: protocol.PlayerLeftPayload
	(*PlayerReadyPayload)(nil),  // 4: protocol.PlayerReadyPayload
	(*GameStartPayload)(nil),    // 5: protocol.GameStartPayload
	(*DealCardsPayload)(nil),    // 6: protocol.DealCardsPayload
	(*BidTurnPayload)(nil),      // 7: protocol.BidTurnPayload
	(*BidResultPayload)(nil),    // 8: protocol.BidResultPayload
	(*LandlordPayload)(nil),     // 9: protocol.LandlordPayload
	(*PlayTurnPayload)(nil),     // 10: protocol.PlayTurnPayload
	(*CardPlayedPayload)(nil),   // 11: protocol.CardPlayedPayload
	(*PlayerPassPayload)(nil),   // 12: protocol.PlayerPassPayload
	(*GameOverPayload)(nil),     // 13: protocol.GameOverPayload
	(*PlayerInfo)(nil),          // 14: protocol.PlayerInfo
	(*CardInfo)(nil),            // 15: protocol.CardInfo
	(*PlayerHand)(nil),          // 16: protocol.PlayerHand
}
var file_internal_network_protocol_proto_game_messages_proto_depIdxs = []int32{
	14, // 0: protocol.RoomCreatedPayload.player:type_name -> protocol.PlayerInfo
	14, // 1: protocol.RoomJoinedPayload.player:type_name -> protocol.PlayerInfo
	14, // 2: protocol.RoomJoinedPayload.players:type_name -> protocol.PlayerInfo
	14, // 3: protocol.PlayerJoinedPayload.player:type_name -> protocol.PlayerInfo
	14, // 4: protocol.GameStartPayload.players:type_name -> protocol.PlayerInfo
	15, // 5: protocol.DealCardsPayload.cards:type_name -> protocol.CardInfo
	15, // 6: protocol.DealCardsPayload.bottom_cards:type_name -> protocol.CardInfo
	15, // 7: protocol.LandlordPayload.bottom_cards:type_name -> protocol.CardInfo
	15, // 8: protocol.CardPlayedPayload.cards:type_name -> protocol.CardInfo
	16, // 9: protocol.GameOverPayload.player_hands:type_name -> protocol.PlayerHand
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_network_protocol_proto_game_messages_proto_init() }
func file_internal_network_protocol_proto_game_messages_proto_init() {
	if File_internal_network_protocol_proto_game_messages_proto != nil {
		return
	}
	file_internal_network_protocol_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_network_protocol_proto_game_messages_proto_rawDesc), len(file_internal_network_protocol_proto_game_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_network_protocol_proto_game_messages_proto_goTypes,
		DependencyIndexes: file_internal_network_protocol_proto_game_messages_proto_depIdxs,
		MessageInfos:      file_internal_network_protocol_proto_game_messages_proto_msgTypes,
	}.Build()
	File_internal_network_protocol_proto_game_messages_proto = out.File
	file_internal_network_protocol_proto_game_messages_proto_goTypes = nil
	file_internal_network_protocol_proto_game_messages_proto_depIdxs = nil
}
