// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/network/protocol/message.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MSG_UNKNOWN MessageType = 0
	// 客户端 -> 服务端
	MessageType_MSG_RECONNECT       MessageType = 1
	MessageType_MSG_PING            MessageType = 2
	MessageType_MSG_CREATE_ROOM     MessageType = 3
	MessageType_MSG_JOIN_ROOM       MessageType = 4
	MessageType_MSG_LEAVE_ROOM      MessageType = 5
	MessageType_MSG_QUICK_MATCH     MessageType = 6
	MessageType_MSG_READY           MessageType = 7
	MessageType_MSG_CANCEL_READY    MessageType = 8
	MessageType_MSG_BID             MessageType = 9
	MessageType_MSG_PLAY_CARDS      MessageType = 10
	MessageType_MSG_PASS            MessageType = 11
	MessageType_MSG_GET_STATS       MessageType = 12
	MessageType_MSG_GET_LEADERBOARD MessageType = 13
	MessageType_MSG_GET_ROOM_LIST   MessageType = 14
	// 服务端 -> 客户端
	MessageType_MSG_CONNECTED          MessageType = 100
	MessageType_MSG_RECONNECTED        MessageType = 101
	MessageType_MSG_PONG               MessageType = 102
	MessageType_MSG_PLAYER_OFFLINE     MessageType = 103
	MessageType_MSG_PLAYER_ONLINE      MessageType = 104
	MessageType_MSG_ONLINE_COUNT       MessageType = 105
	MessageType_MSG_ROOM_CREATED       MessageType = 106
	MessageType_MSG_ROOM_JOINED        MessageType = 107
	MessageType_MSG_PLAYER_JOINED      MessageType = 108
	MessageType_MSG_PLAYER_LEFT        MessageType = 109
	MessageType_MSG_PLAYER_READY       MessageType = 110
	MessageType_MSG_MATCH_FOUND        MessageType = 111
	MessageType_MSG_GAME_START         MessageType = 112
	MessageType_MSG_DEAL_CARDS         MessageType = 113
	MessageType_MSG_BID_TURN           MessageType = 114
	MessageType_MSG_BID_RESULT         MessageType = 115
	MessageType_MSG_LANDLORD           MessageType = 116
	MessageType_MSG_PLAY_TURN          MessageType = 117
	MessageType_MSG_CARD_PLAYED        MessageType = 118
	MessageType_MSG_PLAYER_PASS        MessageType = 119
	MessageType_MSG_GAME_OVER          MessageType = 120
	MessageType_MSG_ROUND_RESULT       MessageType = 121
	MessageType_MSG_STATS_RESULT       MessageType = 122
	MessageType_MSG_LEADERBOARD_RESULT MessageType = 123
	MessageType_MSG_ROOM_LIST_RESULT   MessageType = 124
	MessageType_MSG_ERROR              MessageType = 200
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:   "MSG_UNKNOWN",
		1:   "MSG_RECONNECT",
		2:   "MSG_PING",
		3:   "MSG_CREATE_ROOM",
		4:   "MSG_JOIN_ROOM",
		5:   "MSG_LEAVE_ROOM",
		6:   "MSG_QUICK_MATCH",
		7:   "MSG_READY",
		8:   "MSG_CANCEL_READY",
		9:   "MSG_BID",
		10:  "MSG_PLAY_CARDS",
		11:  "MSG_PASS",
		12:  "MSG_GET_STATS",
		13:  "MSG_GET_LEADERBOARD",
		14:  "MSG_GET_ROOM_LIST",
		100: "MSG_CONNECTED",
		101: "MSG_RECONNECTED",
		102: "MSG_PONG",
		103: "MSG_PLAYER_OFFLINE",
		104: "MSG_PLAYER_ONLINE",
		105: "MSG_ONLINE_COUNT",
		106: "MSG_ROOM_CREATED",
		107: "MSG_ROOM_JOINED",
		108: "MSG_PLAYER_JOINED",
		109: "MSG_PLAYER_LEFT",
		110: "MSG_PLAYER_READY",
		111: "MSG_MATCH_FOUND",
		112: "MSG_GAME_START",
		113: "MSG_DEAL_CARDS",
		114: "MSG_BID_TURN",
		115: "MSG_BID_RESULT",
		116: "MSG_LANDLORD",
		117: "MSG_PLAY_TURN",
		118: "MSG_CARD_PLAYED",
		119: "MSG_PLAYER_PASS",
		120: "MSG_GAME_OVER",
		121: "MSG_ROUND_RESULT",
		122: "MSG_STATS_RESULT",
		123: "MSG_LEADERBOARD_RESULT",
		124: "MSG_ROOM_LIST_RESULT",
		200: "MSG_ERROR",
	}
	MessageType_value = map[string]int32{
		"MSG_UNKNOWN":            0,
		"MSG_RECONNECT":          1,
		"MSG_PING":               2,
		"MSG_CREATE_ROOM":        3,
		"MSG_JOIN_ROOM":          4,
		"MSG_LEAVE_ROOM":         5,
		"MSG_QUICK_MATCH":        6,
		"MSG_READY":              7,
		"MSG_CANCEL_READY":       8,
		"MSG_BID":                9,
		"MSG_PLAY_CARDS":         10,
		"MSG_PASS":               11,
		"MSG_GET_STATS":          12,
		"MSG_GET_LEADERBOARD":    13,
		"MSG_GET_ROOM_LIST":      14,
		"MSG_CONNECTED":          100,
		"MSG_RECONNECTED":        101,
		"MSG_PONG":               102,
		"MSG_PLAYER_OFFLINE":     103,
		"MSG_PLAYER_ONLINE":      104,
		"MSG_ONLINE_COUNT":       105,
		"MSG_ROOM_CREATED":       106,
		"MSG_ROOM_JOINED":        107,
		"MSG_PLAYER_JOINED":      108,
		"MSG_PLAYER_LEFT":        109,
		"MSG_PLAYER_READY":       110,
		"MSG_MATCH_FOUND":        111,
		"MSG_GAME_START":         112,
		"MSG_DEAL_CARDS":         113,
		"MSG_BID_TURN":           114,
		"MSG_BID_RESULT":         115,
		"MSG_LANDLORD":           116,
		"MSG_PLAY_TURN":          117,
		"MSG_CARD_PLAYED":        118,
		"MSG_PLAYER_PASS":        119,
		"MSG_GAME_OVER":          120,
		"MSG_ROUND_RESULT":       121,
		"MSG_STATS_RESULT":       122,
		"MSG_LEADERBOARD_RESULT": 123,
		"MSG_ROOM_LIST_RESULT":   124,
		"MSG_ERROR":              200,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_network_protocol_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_internal_network_protocol_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_network_protocol_message_proto_rawDescGZIP(), []int{0}
}

// Message 所有消息的外层包装
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_network_protocol_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MSG_UNKNOWN
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_internal_network_protocol_message_proto protoreflect.FileDescriptor

const file_internal_network_protocol_message_proto_rawDesc = "" +
	"\n" +
	"'internal/network/protocol/message.proto\x12\bprotocol\x1a&internal/network/protocol/common.proto\x1a/internal/network/protocol/client_messages.proto\x1a/internal/network/protocol/server_messages.proto\x1a-internal/network/protocol/game_messages.proto\"N\n" +
	"\aMessage\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.protocol.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload*\xc6\x06\n" +
	"\vMessageType\x12\x0f\n" +
	"\vMSG_UNKNOWN\x10\x00\x12\x11\n" +
	"\rMSG_RECONNECT\x10\x01\x12\f\n" +
	"\bMSG_PING\x10\x02\x12\x13\n" +
	"\x0fMSG_CREATE_ROOM\x10\x03\x12\x11\n" +
	"\rMSG_JOIN_ROOM\x10\x04\x12\x12\n" +
	"\x0eMSG_LEAVE_ROOM\x10\x05\x12\x13\n" +
	"\x0fMSG_QUICK_MATCH\x10\x06\x12\r\n" +
	"\tMSG_READY\x10\a\x12\x14\n" +
	"\x10MSG_CANCEL_READY\x10\b\x12\v\n" +
	"\aMSG_BID\x10\t\x12\x12\n" +
	"\x0eMSG_PLAY_CARDS\x10\n" +
	"\x12\f\n" +
	"\bMSG_PASS\x10\v\x12\x11\n" +
	"\rMSG_GET_STATS\x10\f\x12\x17\n" +
	"\x13MSG_GET_LEADERBOARD\x10\r\x12\x15\n" +
	"\x11MSG_GET_ROOM_LIST\x10\x0e\x12\x11\n" +
	"\rMSG_CONNECTED\x10d\x12\x13\n" +
	"\x0fMSG_RECONNECTED\x10e\x12\f\n" +
	"\bMSG_PONG\x10f\x12\x16\n" +
	"\x12MSG_PLAYER_OFFLINE\x10g\x12\x15\n" +
	"\x11MSG_PLAYER_ONLINE\x10h\x12\x14\n" +
	"\x10MSG_ONLINE_COUNT\x10i\x12\x14\n" +
	"\x10MSG_ROOM_CREATED\x10j\x12\x13\n" +
	"\x0fMSG_ROOM_JOINED\x10k\x12\x15\n" +
	"\x11MSG_PLAYER_JOINED\x10l\x12\x13\n" +
	"\x0fMSG_PLAYER_LEFT\x10m\x12\x14\n" +
	"\x10MSG_PLAYER_READY\x10n\x12\x13\n" +
	"\x0fMSG_MATCH_FOUND\x10o\x12\x12\n" +
	"\x0eMSG_GAME_START\x10p\x12\x12\n" +
	"\x0eMSG_DEAL_CARDS\x10q\x12\x10\n" +
	"\fMSG_BID_TURN\x10r\x12\x12\n" +
	"\x0eMSG_BID_RESULT\x10s\x12\x10\n" +
	"\fMSG_LANDLORD\x10t\x12\x11\n" +
	"\rMSG_PLAY_TURN\x10u\x12\x13\n" +
	"\x0fMSG_CARD_PLAYED\x10v\x12\x13\n" +
	"\x0fMSG_PLAYER_PASS\x10w\x12\x11\n" +
	"\rMSG_GAME_OVER\x10x\x12\x14\n" +
	"\x10MSG_ROUND_RESULT\x10y\x12\x14\n" +
	"\x10MSG_STATS_RESULT\x10z\x12\x1a\n" +
	"\x16MSG_LEADERBOARD_RESULT\x10{\x12\x18\n" +
	"\x14MSG_ROOM_LIST_RESULT\x10|\x12\x0e\n" +
	"\tMSG_ERROR\x10\xc8\x01BEZCgithub.com/palemoky/fight-the-landlord/internal/network/protocol/pbb\x06proto3"

var (
	file_internal_network_protocol_message_proto_rawDescOnce sync.Once
	file_internal_network_protocol_message_proto_rawDescData []byte
)

func file_internal_network_protocol_message_proto_rawDescGZIP() []byte {
	file_internal_network_protocol_message_proto_rawDescOnce.Do(func() {
		file_internal_network_protocol_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_network_protocol_message_proto_rawDesc), len(file_internal_network_protocol_message_proto_rawDesc)))
	})
	return file_internal_network_protocol_message_proto_rawDescData
}

var (
	file_internal_network_protocol_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
	file_internal_network_protocol_message_proto_msgTypes  = make([]protoimpl.MessageInfo, 1)
	file_internal_network_protocol_message_proto_goTypes   = []any{
		(MessageType)(0), // 0: protocol.MessageType
		(*Message)(nil),  // 1: protocol.Message
	}
)

var file_internal_network_protocol_message_proto_depIdxs = []int32{
	0, // 0: protocol.Message.type:type_name -> protocol.MessageType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_network_protocol_message_proto_init() }
func file_internal_network_protocol_message_proto_init() {
	if File_internal_network_protocol_message_proto != nil {
		return
	}
	file_internal_network_protocol_common_proto_init()
	file_internal_network_protocol_client_messages_proto_init()
	file_internal_network_protocol_server_messages_proto_init()
	file_internal_network_protocol_game_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_network_protocol_message_proto_rawDesc), len(file_internal_network_protocol_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_network_protocol_message_proto_goTypes,
		DependencyIndexes: file_internal_network_protocol_message_proto_depIdxs,
		EnumInfos:         file_internal_network_protocol_message_proto_enumTypes,
		MessageInfos:      file_internal_network_protocol_message_proto_msgTypes,
	}.Build()
	File_internal_network_protocol_message_proto = out.File
	file_internal_network_protocol_message_proto_goTypes = nil
	file_internal_network_protocol_message_proto_depIdxs = nil
}
