// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/network/protocol/proto/server_messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConnectedPayload 连接成功响应
type ConnectedPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName     string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	ReconnectToken string                 `protobuf:"bytes,3,opt,name=reconnect_token,json=reconnectToken,proto3" json:"reconnect_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectedPayload) Reset() {
	*x = ConnectedPayload{}
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedPayload) ProtoMessage() {}

func (x *ConnectedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedPayload.ProtoReflect.Descriptor instead.
func (*ConnectedPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_server_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectedPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ConnectedPayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *ConnectedPayload) GetReconnectToken() string {
	if x != nil {
		return x.ReconnectToken
	}
	return ""
}

// ReconnectedPayload 重连成功响应
type ReconnectedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	RoomCode      string                 `protobuf:"bytes,3,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	GameState     *GameStateDTO          `protobuf:"bytes,4,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconnectedPayload) Reset() {
	*x = ReconnectedPayload{}
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectedPayload) ProtoMessage() {}

func (x *ReconnectedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectedPayload.ProtoReflect.Descriptor instead.
func (*ReconnectedPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_server_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ReconnectedPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ReconnectedPayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *ReconnectedPayload) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *ReconnectedPayload) GetGameState() *GameStateDTO {
	if x != nil {
		return x.GameState
	}
	return nil
}

// PongPayload 心跳响应
type PongPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientTimestamp int64                  `protobuf:"varint,1,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PongPayload) Reset() {
	*x = PongPayload{}
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongPayload) ProtoMessage() {}

func (x *PongPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongPayload.ProtoReflect.Descriptor instead.
func (*PongPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_server_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PongPayload) GetClientTimestamp() int64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

func (x *PongPayload) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

// PlayerOfflinePayload 玩家掉线通知
type PlayerOfflinePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerOfflinePayload) Reset() {
	*x = PlayerOfflinePayload{}
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerOfflinePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOfflinePayload) ProtoMessage() {}

func (x *PlayerOfflinePayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOfflinePayload.ProtoReflect.Descriptor instead.
func (*PlayerOfflinePayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_server_messages_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerOfflinePayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerOfflinePayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerOfflinePayload) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// PlayerOnlinePayload 玩家上线通知
type PlayerOnlinePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerOnlinePayload) Reset() {
	*x = PlayerOnlinePayload{}
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerOnlinePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOnlinePayload) ProtoMessage() {}

func (x *PlayerOnlinePayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOnlinePayload.ProtoReflect.Descriptor instead.
func (*PlayerOnlinePayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_server_messages_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerOnlinePayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerOnlinePayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// OnlineCountPayload 在线人数更新
type OnlineCountPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineCountPayload) Reset() {
	*x = OnlineCountPayload{}
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineCountPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineCountPayload) ProtoMessage() {}

func (x *OnlineCountPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineCountPayload.ProtoReflect.Descriptor instead.
func (*OnlineCountPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_server_messages_proto_rawDescGZIP(), []int{5}
}

func (x *OnlineCountPayload) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// MaintenanceStatusPayload 维护状态响应
type MaintenanceStatusPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Maintenance   bool                   `protobuf:"varint,1,opt,name=maintenance,proto3" json:"maintenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceStatusPayload) Reset() {
	*x = MaintenanceStatusPayload{}
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceStatusPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceStatusPayload) ProtoMessage() {}

func (x *MaintenanceStatusPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceStatusPayload.ProtoReflect.Descriptor instead.
func (*MaintenanceStatusPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_server_messages_proto_rawDescGZIP(), []int{6}
}

func (x *MaintenanceStatusPayload) GetMaintenance() bool {
	if x != nil {
		return x.Maintenance
	}
	return false
}

// MaintenancePayload 维护模式通知
type MaintenancePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Maintenance   bool                   `protobuf:"varint,1,opt,name=maintenance,proto3" json:"maintenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenancePayload) Reset() {
	*x = MaintenancePayload{}
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenancePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenancePayload) ProtoMessage() {}

func (x *MaintenancePayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenancePayload.ProtoReflect.Descriptor instead.
func (*MaintenancePayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_server_messages_proto_rawDescGZIP(), []int{7}
}

func (x *MaintenancePayload) GetMaintenance() bool {
	if x != nil {
		return x.Maintenance
	}
	return false
}

// ErrorPayload 错误响应
type ErrorPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorPayload) Reset() {
	*x = ErrorPayload{}
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorPayload) ProtoMessage() {}

func (x *ErrorPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorPayload.ProtoReflect.Descriptor instead.
func (*ErrorPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_server_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorPayload) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StatsResultPayload 个人统计结果
type StatsResultPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	TotalGames    int32                  `protobuf:"varint,3,opt,name=total_games,json=totalGames,proto3" json:"total_games,omitempty"`
	Wins          int32                  `protobuf:"varint,4,opt,name=wins,proto3" json:"wins,omitempty"`
	Losses        int32                  `protobuf:"varint,5,opt,name=losses,proto3" json:"losses,omitempty"`
	WinRate       float64                `protobuf:"fixed64,6,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	LandlordGames int32                  `protobuf:"varint,7,opt,name=landlord_games,json=landlordGames,proto3" json:"landlord_games,omitempty"`
	LandlordWins  int32                  `protobuf:"varint,8,opt,name=landlord_wins,json=landlordWins,proto3" json:"landlord_wins,omitempty"`
	FarmerGames   int32                  `protobuf:"varint,9,opt,name=farmer_games,json=farmerGames,proto3" json:"farmer_games,omitempty"`
	FarmerWins    int32                  `protobuf:"varint,10,opt,name=farmer_wins,json=farmerWins,proto3" json:"farmer_wins,omitempty"`
	Score         int32                  `protobuf:"varint,11,opt,name=score,proto3" json:"score,omitempty"`
	Rank          int32                  `protobuf:"varint,12,opt,name=rank,proto3" json:"rank,omitempty"`
	CurrentStreak int32                  `protobuf:"varint,13,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`
	MaxWinStreak  int32                  `protobuf:"varint,14,opt,name=max_win_streak,json=maxWinStreak,proto3" json:"max_win_streak,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResultPayload) Reset() {
	*x = StatsResultPayload{}
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResultPayload) ProtoMessage() {}

func (x *StatsResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResultPayload.ProtoReflect.Descriptor instead.
func (*StatsResultPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_server_messages_proto_rawDescGZIP(), []int{9}
}

func (x *StatsResultPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *StatsResultPayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *StatsResultPayload) GetTotalGames() int32 {
	if x != nil {
		return x.TotalGames
	}
	return 0
}

func (x *StatsResultPayload) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *StatsResultPayload) GetLosses() int32 {
	if x != nil {
		return x.Losses
	}
	return 0
}

func (x *StatsResultPayload) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *StatsResultPayload) GetLandlordGames() int32 {
	if x != nil {
		return x.LandlordGames
	}
	return 0
}

func (x *StatsResultPayload) GetLandlordWins() int32 {
	if x != nil {
		return x.LandlordWins
	}
	return 0
}

func (x *StatsResultPayload) GetFarmerGames() int32 {
	if x != nil {
		return x.FarmerGames
	}
	return 0
}

func (x *StatsResultPayload) GetFarmerWins() int32 {
	if x != nil {
		return x.FarmerWins
	}
	return 0
}

func (x *StatsResultPayload) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *StatsResultPayload) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *StatsResultPayload) GetCurrentStreak() int32 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

func (x *StatsResultPayload) GetMaxWinStreak() int32 {
	if x != nil {
		return x.MaxWinStreak
	}
	return 0
}

// LeaderboardResultPayload 排行榜结果
type LeaderboardResultPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardResultPayload) Reset() {
	*x = LeaderboardResultPayload{}
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardResultPayload) ProtoMessage() {}

func (x *LeaderboardResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardResultPayload.ProtoReflect.Descriptor instead.
func (*LeaderboardResultPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_server_messages_proto_rawDescGZIP(), []int{10}
}

func (x *LeaderboardResultPayload) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LeaderboardResultPayload) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// RoomListResultPayload 房间列表结果
type RoomListResultPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomListItem        `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListResultPayload) Reset() {
	*x = RoomListResultPayload{}
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListResultPayload) ProtoMessage() {}

func (x *RoomListResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_protocol_proto_server_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListResultPayload.ProtoReflect.Descriptor instead.
func (*RoomListResultPayload) Descriptor() ([]byte, []int) {
	return file_internal_network_protocol_proto_server_messages_proto_rawDescGZIP(), []int{11}
}

func (x *RoomListResultPayload) GetRooms() []*RoomListItem {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_internal_network_protocol_proto_server_messages_proto protoreflect.FileDescriptor

const file_internal_network_protocol_proto_server_messages_proto_rawDesc = "" +
	"\n" +
	"5internal/network/protocol/proto/server_messages.proto\x12\bprotocol\x1a,internal/network/protocol/proto/common.proto\"y\n" +
	"\x10ConnectedPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12'\n" +
	"\x0freconnect_token\x18\x03 \x01(\tR\x0ereconnectToken\"\xa6\x01\n" +
	"\x12ReconnectedPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x1b\n" +
	"\troom_code\x18\x03 \x01(\tR\broomCode\x125\n" +
	"\n" +
	"game_state\x18\x04 \x01(\v2\x16.protocol.GameStateDTOR\tgameState\"c\n" +
	"\vPongPayload\x12)\n" +
	"\x10client_timestamp\x18\x01 \x01(\x03R\x0fclientTimestamp\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x03R\x0fserverTimestamp\"n\n" +
	"\x14PlayerOfflinePayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\"S\n" +
	"\x13PlayerOnlinePayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"*\n" +
	"\x12OnlineCountPayload\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"<\n" +
	"\x18MaintenanceStatusPayload\x12 \n" +
	"\vmaintenance\x18\x01 \x01(\bR\vmaintenance\"6\n" +
	"\x12MaintenancePayload\x12 \n" +
	"\vmaintenance\x18\x01 \x01(\bR\vmaintenance\"<\n" +
	"\fErrorPayload\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc1\x03\n" +
	"\x12StatsResultPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x1f\n" +
	"\vtotal_games\x18\x03 \x01(\x05R\n" +
	"totalGames\x12\x12\n" +
	"\x04wins\x18\x04 \x01(\x05R\x04wins\x12\x16\n" +
	"\x06losses\x18\x05 \x01(\x05R\x06losses\x12\x19\n" +
	"\bwin_rate\x18\x06 \x01(\x01R\awinRate\x12%\n" +
	"\x0elandlord_games\x18\a \x01(\x05R\rlandlordGames\x12#\n" +
	"\rlandlord_wins\x18\b \x01(\x05R\flandlordWins\x12!\n" +
	"\ffarmer_games\x18\t \x01(\x05R\vfarmerGames\x12\x1f\n" +
	"\vfarmer_wins\x18\n" +
	" \x01(\x05R\n" +
	"farmerWins\x12\x14\n" +
	"\x05score\x18\v \x01(\x05R\x05score\x12\x12\n" +
	"\x04rank\x18\f \x01(\x05R\x04rank\x12%\n" +
	"\x0ecurrent_streak\x18\r \x01(\x05R\rcurrentStreak\x12$\n" +
	"\x0emax_win_streak\x18\x0e \x01(\x05R\fmaxWinStreak\"d\n" +
	"\x18LeaderboardResultPayload\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x124\n" +
	"\aentries\x18\x02 \x03(\v2\x1a.protocol.LeaderboardEntryR\aentries\"E\n" +
	"\x15RoomListResultPayload\x12,\n" +
	"\x05rooms\x18\x01 \x03(\v2\x16.protocol.RoomListItemR\x05roomsBEZCgithub.com/palemoky/fight-the-landlord/internal/network/protocol/pbb\x06proto3"

var (
	file_internal_network_protocol_proto_server_messages_proto_rawDescOnce sync.Once
	file_internal_network_protocol_proto_server_messages_proto_rawDescData []byte
)

func file_internal_network_protocol_proto_server_messages_proto_rawDescGZIP() []byte {
	file_internal_network_protocol_proto_server_messages_proto_rawDescOnce.Do(func() {
		file_internal_network_protocol_proto_server_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_network_protocol_proto_server_messages_proto_rawDesc), len(file_internal_network_protocol_proto_server_messages_proto_rawDesc)))
	})
	return file_internal_network_protocol_proto_server_messages_proto_rawDescData
}

var file_internal_network_protocol_proto_server_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_network_protocol_proto_server_messages_proto_goTypes = []any{
	(*ConnectedPayload)(nil),         // 0: protocol.ConnectedPayload
	(*ReconnectedPayload)(nil),       // 1: protocol.ReconnectedPayload
	(*PongPayload)(nil),              // 2: protocol.PongPayload
	(*PlayerOfflinePayload)(nil),     // 3: protocol.PlayerOfflinePayload
	(*PlayerOnlinePayload)(nil),      // 4: protocol.PlayerOnlinePayload
	(*OnlineCountPayload)(nil),       // 5: protocol.OnlineCountPayload
	(*MaintenanceStatusPayload)(nil), // 6: protocol.MaintenanceStatusPayload
	(*MaintenancePayload)(nil),       // 7: protocol.MaintenancePayload
	(*ErrorPayload)(nil),             // 8: protocol.ErrorPayload
	(*StatsResultPayload)(nil),       // 9: protocol.StatsResultPayload
	(*LeaderboardResultPayload)(nil), // 10: protocol.LeaderboardResultPayload
	(*RoomListResultPayload)(nil),    // 11: protocol.RoomListResultPayload
	(*GameStateDTO)(nil),             // 12: protocol.GameStateDTO
	(*LeaderboardEntry)(nil),         // 13: protocol.LeaderboardEntry
	(*RoomListItem)(nil),             // 14: protocol.RoomListItem
}
var file_internal_network_protocol_proto_server_messages_proto_depIdxs = []int32{
	12, // 0: protocol.ReconnectedPayload.game_state:type_name -> protocol.GameStateDTO
	13, // 1: protocol.LeaderboardResultPayload.entries:type_name -> protocol.LeaderboardEntry
	14, // 2: protocol.RoomListResultPayload.rooms:type_name -> protocol.RoomListItem
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_network_protocol_proto_server_messages_proto_init() }
func file_internal_network_protocol_proto_server_messages_proto_init() {
	if File_internal_network_protocol_proto_server_messages_proto != nil {
		return
	}
	file_internal_network_protocol_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_network_protocol_proto_server_messages_proto_rawDesc), len(file_internal_network_protocol_proto_server_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_network_protocol_proto_server_messages_proto_goTypes,
		DependencyIndexes: file_internal_network_protocol_proto_server_messages_proto_depIdxs,
		MessageInfos:      file_internal_network_protocol_proto_server_messages_proto_msgTypes,
	}.Build()
	File_internal_network_protocol_proto_server_messages_proto = out.File
	file_internal_network_protocol_proto_server_messages_proto_goTypes = nil
	file_internal_network_protocol_proto_server_messages_proto_depIdxs = nil
}
