# golangci-lint configuration v2
# https://golangci-lint.run/docs/configuration/file

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  # 禁用所有默认 linters，只启用明确指定的
  default: none

  # 启用推荐的 linters
  enable:
    # 基础检查
    - govet # 官方静态分析工具
    - errcheck # 检查未处理的错误
    - staticcheck # 综合静态分析 (包含 gosimple, unused)
    - ineffassign # 检测无效的赋值

    # 代码质量
    - gocritic # 提供代码质量建议
    - gocyclo # 检查圈复杂度
    - gocognit # 检查认知复杂度
    - funlen # 检查函数长度
    - nestif # 检查深度嵌套的 if 语句

    # 错误处理
    - errorlint # 检查 Go 1.13+ 错误包装
    - nilerr # 检查返回 nil 但错误不为 nil 的情况

    # 性能
    - prealloc # 检查可以预分配的 slice
    - bodyclose # 检查 HTTP response body 是否关闭
    - sqlclosecheck # 检查 sql.Rows/Stmt 是否关闭

    # 安全
    - gosec # 安全检查

    # 风格
    - misspell # 拼写检查
    - unconvert # 检查不必要的类型转换
    - usestdlibvars # 推荐使用标准库常量
    - unparam # 检查未使用的函数参数
    - nakedret # 检查裸返回
    - dogsled # 检查过多的空白标识符赋值
    - whitespace # 检查不必要的空行

    # 测试
    - thelper # 检测测试辅助函数是否调用 t.Helper()
    - tparallel # 检测 t.Parallel() 的不当使用

  settings:
    govet:
      enable-all: true
      disable:
        - shadow # 变量遮蔽检查可能过于严格
        - fieldalignment # 字段对齐优化对小项目意义不大

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - unlambda # 不强制将 lambda 替换为函数引用
        - hugeParam # 对于游戏逻辑，大参数有时是必要的
        - importShadow # 导入遮蔽检查过于严格

    gocyclo:
      min-complexity: 15 # 圈复杂度阈值

    gocognit:
      min-complexity: 30 # 认知复杂度阈值

    funlen:
      lines: 100 # 函数最大行数
      statements: 60 # 函数最大语句数

    nestif:
      min-complexity: 5 # 嵌套复杂度阈值

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30 # 允许裸返回的最大函数行数

    gosec:
      excludes:
        - G404 # 使用弱随机数生成器

    errorlint:
      errorf: true
      asserts: true
      comparison: true

  # 排除规则 (v2 格式)
  exclusions:
    # 生成文件排除模式
    generated: lax

    # 预设排除规则
    presets:
      - comments
      - std-error-handling
      - common-false-positives

    # 自定义排除规则
    rules:
      # 测试文件中放宽某些检查
      - path: _test\.go
        linters:
          - errcheck
          - dupl
          - funlen
          - gocyclo
          - gocognit

      # main 函数和 init 函数允许更长
      - source: "^func (main|init)\\("
        linters:
          - funlen

    # 排除的路径
    paths:
      - internal/protocol/pb
      - internal/protocol/convert/msgtype/mapping.go

issues:
  # 最大问题数 (0 = 无限制)
  max-issues-per-linter: 0
  max-same-issues: 0
