# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    project:
      default:
        # Don't fail CI on coverage decrease
        informational: true
    patch:
      default:
        informational: true

ignore:
  # UI code is tightly coupled with bubbletea framework and difficult to unit test
  - "internal/ui/**/*"
  # Main entry points
  - "cmd/**/*"
  # Network code requires integration tests
  - "internal/network/**/*"
  # Config code is simple and mostly just parsing
  - "internal/config/**/*"
