// Code generated by gen_message_type.go; DO NOT EDIT.

package msgtype

import (
	"github.com/palemoky/fight-the-landlord/internal/protocol/pb"
)

// stringToProtoMap 字符串到 protobuf 枚举的映射表
var stringToProtoMap = map[string]pb.MessageType{
	"unknown": pb.MessageType_MSG_UNKNOWN,
	"reconnect": pb.MessageType_MSG_RECONNECT,
	"ping": pb.MessageType_MSG_PING,
	"create_room": pb.MessageType_MSG_CREATE_ROOM,
	"join_room": pb.MessageType_MSG_JOIN_ROOM,
	"leave_room": pb.MessageType_MSG_LEAVE_ROOM,
	"quick_match": pb.MessageType_MSG_QUICK_MATCH,
	"ready": pb.MessageType_MSG_READY,
	"cancel_ready": pb.MessageType_MSG_CANCEL_READY,
	"bid": pb.MessageType_MSG_BID,
	"play_cards": pb.MessageType_MSG_PLAY_CARDS,
	"pass": pb.MessageType_MSG_PASS,
	"get_stats": pb.MessageType_MSG_GET_STATS,
	"get_leaderboard": pb.MessageType_MSG_GET_LEADERBOARD,
	"get_room_list": pb.MessageType_MSG_GET_ROOM_LIST,
	"get_online_count": pb.MessageType_MSG_GET_ONLINE_COUNT,
	"get_maintenance_status": pb.MessageType_MSG_GET_MAINTENANCE_STATUS,
	"chat": pb.MessageType_MSG_CHAT,
	"connected": pb.MessageType_MSG_CONNECTED,
	"reconnected": pb.MessageType_MSG_RECONNECTED,
	"pong": pb.MessageType_MSG_PONG,
	"player_offline": pb.MessageType_MSG_PLAYER_OFFLINE,
	"player_online": pb.MessageType_MSG_PLAYER_ONLINE,
	"online_count": pb.MessageType_MSG_ONLINE_COUNT,
	"room_created": pb.MessageType_MSG_ROOM_CREATED,
	"room_joined": pb.MessageType_MSG_ROOM_JOINED,
	"player_joined": pb.MessageType_MSG_PLAYER_JOINED,
	"player_left": pb.MessageType_MSG_PLAYER_LEFT,
	"player_ready": pb.MessageType_MSG_PLAYER_READY,
	"match_found": pb.MessageType_MSG_MATCH_FOUND,
	"game_start": pb.MessageType_MSG_GAME_START,
	"deal_cards": pb.MessageType_MSG_DEAL_CARDS,
	"bid_turn": pb.MessageType_MSG_BID_TURN,
	"bid_result": pb.MessageType_MSG_BID_RESULT,
	"landlord": pb.MessageType_MSG_LANDLORD,
	"play_turn": pb.MessageType_MSG_PLAY_TURN,
	"card_played": pb.MessageType_MSG_CARD_PLAYED,
	"player_pass": pb.MessageType_MSG_PLAYER_PASS,
	"game_over": pb.MessageType_MSG_GAME_OVER,
	"round_result": pb.MessageType_MSG_ROUND_RESULT,
	"stats_result": pb.MessageType_MSG_STATS_RESULT,
	"leaderboard_result": pb.MessageType_MSG_LEADERBOARD_RESULT,
	"room_list_result": pb.MessageType_MSG_ROOM_LIST_RESULT,
	"maintenance_status": pb.MessageType_MSG_MAINTENANCE_STATUS,
	"maintenance": pb.MessageType_MSG_MAINTENANCE,
	"error": pb.MessageType_MSG_ERROR,
}

// protoToStringMap protobuf 枚举到字符串的映射表
var protoToStringMap = map[pb.MessageType]string{
	pb.MessageType_MSG_UNKNOWN: "unknown",
	pb.MessageType_MSG_RECONNECT: "reconnect",
	pb.MessageType_MSG_PING: "ping",
	pb.MessageType_MSG_CREATE_ROOM: "create_room",
	pb.MessageType_MSG_JOIN_ROOM: "join_room",
	pb.MessageType_MSG_LEAVE_ROOM: "leave_room",
	pb.MessageType_MSG_QUICK_MATCH: "quick_match",
	pb.MessageType_MSG_READY: "ready",
	pb.MessageType_MSG_CANCEL_READY: "cancel_ready",
	pb.MessageType_MSG_BID: "bid",
	pb.MessageType_MSG_PLAY_CARDS: "play_cards",
	pb.MessageType_MSG_PASS: "pass",
	pb.MessageType_MSG_GET_STATS: "get_stats",
	pb.MessageType_MSG_GET_LEADERBOARD: "get_leaderboard",
	pb.MessageType_MSG_GET_ROOM_LIST: "get_room_list",
	pb.MessageType_MSG_GET_ONLINE_COUNT: "get_online_count",
	pb.MessageType_MSG_GET_MAINTENANCE_STATUS: "get_maintenance_status",
	pb.MessageType_MSG_CHAT: "chat",
	pb.MessageType_MSG_CONNECTED: "connected",
	pb.MessageType_MSG_RECONNECTED: "reconnected",
	pb.MessageType_MSG_PONG: "pong",
	pb.MessageType_MSG_PLAYER_OFFLINE: "player_offline",
	pb.MessageType_MSG_PLAYER_ONLINE: "player_online",
	pb.MessageType_MSG_ONLINE_COUNT: "online_count",
	pb.MessageType_MSG_ROOM_CREATED: "room_created",
	pb.MessageType_MSG_ROOM_JOINED: "room_joined",
	pb.MessageType_MSG_PLAYER_JOINED: "player_joined",
	pb.MessageType_MSG_PLAYER_LEFT: "player_left",
	pb.MessageType_MSG_PLAYER_READY: "player_ready",
	pb.MessageType_MSG_MATCH_FOUND: "match_found",
	pb.MessageType_MSG_GAME_START: "game_start",
	pb.MessageType_MSG_DEAL_CARDS: "deal_cards",
	pb.MessageType_MSG_BID_TURN: "bid_turn",
	pb.MessageType_MSG_BID_RESULT: "bid_result",
	pb.MessageType_MSG_LANDLORD: "landlord",
	pb.MessageType_MSG_PLAY_TURN: "play_turn",
	pb.MessageType_MSG_CARD_PLAYED: "card_played",
	pb.MessageType_MSG_PLAYER_PASS: "player_pass",
	pb.MessageType_MSG_GAME_OVER: "game_over",
	pb.MessageType_MSG_ROUND_RESULT: "round_result",
	pb.MessageType_MSG_STATS_RESULT: "stats_result",
	pb.MessageType_MSG_LEADERBOARD_RESULT: "leaderboard_result",
	pb.MessageType_MSG_ROOM_LIST_RESULT: "room_list_result",
	pb.MessageType_MSG_MAINTENANCE_STATUS: "maintenance_status",
	pb.MessageType_MSG_MAINTENANCE: "maintenance",
	pb.MessageType_MSG_ERROR: "error",
}

// StringToProtoMessageType 字符串消息类型转 protobuf 枚举
func StringToProtoMessageType(s string) pb.MessageType {
	if t, ok := stringToProtoMap[s]; ok {
		return t
	}
	return pb.MessageType_MSG_UNKNOWN
}

// ProtoMessageTypeToString protobuf 枚举转字符串消息类型
func ProtoMessageTypeToString(t pb.MessageType) string {
	if s, ok := protoToStringMap[t]; ok {
		return s
	}
	return "unknown"
}
