//go:build ignore

package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strings"
)

// 代码生成器：从 message.proto 生成 protobuf 映射函数
func main() {
	// 读取 proto 文件
	protoFile := "../proto/message.proto"
	file, err := os.Open(protoFile)
	if err != nil {
		panic(err)
	}
	defer file.Close()

	// 解析枚举
	var mappings []struct {
		stringName string
		protoName  string
	}

	scanner := bufio.NewScanner(file)
	inEnum := false
	enumPattern := regexp.MustCompile(`^\s*MSG_(\w+)\s*=`)

	for scanner.Scan() {
		line := scanner.Text()

		if strings.Contains(line, "enum MessageType") {
			inEnum = true
			continue
		}

		if inEnum && strings.Contains(line, "}") {
			break
		}

		if inEnum {
			matches := enumPattern.FindStringSubmatch(line)
			if len(matches) > 1 {
				enumName := matches[1]
				// MSG_RECONNECT -> reconnect
				stringName := strings.ToLower(enumName)
				protoName := "MSG_" + enumName

				mappings = append(mappings, struct {
					stringName string
					protoName  string
				}{stringName, protoName})
			}
		}
	}

	// 生成代码
	output, err := os.Create("message_type_generated.go")
	if err != nil {
		panic(err)
	}
	defer output.Close()

	fmt.Fprintln(output, "// Code generated by gen_message_type.go; DO NOT EDIT.")
	fmt.Fprintln(output, "")
	fmt.Fprintln(output, "package convert")
	fmt.Fprintln(output, "")
	fmt.Fprintln(output, "import (")
	fmt.Fprintln(output, "\t\"github.com/palemoky/fight-the-landlord/internal/network/protocol/pb\"")
	fmt.Fprintln(output, ")")
	fmt.Fprintln(output, "")

	// StringToProtoMessageType
	fmt.Fprintln(output, "// StringToProtoMessageType 字符串消息类型转 protobuf 枚举")
	fmt.Fprintln(output, "func StringToProtoMessageType(s string) pb.MessageType {")
	fmt.Fprintln(output, "\tswitch s {")
	for _, m := range mappings {
		fmt.Fprintf(output, "\tcase \"%s\":\n", m.stringName)
		fmt.Fprintf(output, "\t\treturn pb.MessageType_%s\n", m.protoName)
	}
	fmt.Fprintln(output, "\tdefault:")
	fmt.Fprintln(output, "\t\treturn pb.MessageType_MSG_UNKNOWN")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "}")
	fmt.Fprintln(output, "")

	// ProtoMessageTypeToString
	fmt.Fprintln(output, "// ProtoMessageTypeToString protobuf 枚举转字符串消息类型")
	fmt.Fprintln(output, "func ProtoMessageTypeToString(t pb.MessageType) string {")
	fmt.Fprintln(output, "\tswitch t {")
	for _, m := range mappings {
		fmt.Fprintf(output, "\tcase pb.MessageType_%s:\n", m.protoName)
		fmt.Fprintf(output, "\t\treturn \"%s\"\n", m.stringName)
	}
	fmt.Fprintln(output, "\tdefault:")
	fmt.Fprintln(output, "\t\treturn \"unknown\"")
	fmt.Fprintln(output, "\t}")
	fmt.Fprintln(output, "}")

	fmt.Println("✅ 代码生成完成: message_type_generated.go")
}
